export interface School {
  id: number;
  name: string;
  slug: string;
  location: string;
  region: string;
  type: string;
  students: number;
  rating: number;
  fees: string;
  image: string;
  description: string;
}

// List of available school images
const schoolImagesList = [
  "/school-images/hailemanas1.jpg",
  "/school-images/hailemanas2.jpg",
  "/school-images/hailemanas3.jpg",
  "/school-images/hailemanas4.jpg",
  "/school-images/odaspecial2.jpg",
  "/school-images/hailemanas6.jpg",
  "/school-images/odaspecial3.jpg",
  "/school-images/amboifaboru.jpg",
];

// Function to randomly select an image from the list
const getRandomSchoolImage = (): string => {
  const randomIndex = Math.floor(Math.random() * schoolImagesList.length);
  return schoolImagesList[randomIndex];
};

export const schools: School[] = [
  {
    id: 1,
    name: "Addis Ababa International Boarding School",
    slug: "addis-ababa-international",
    location: "Addis Ababa",
    region: "Addis Ababa",
    type: "International",
    students: 850,
    rating: 4.8,
    fees: "45,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Premier international boarding school offering world-class education in Ethiopia's capital.",
  },
  {
    id: 2,
    name: "Blue Nile Academy",
    slug: "blue-nile-academy",
    location: "Bahir Dar",
    region: "Amhara",
    type: "Private",
    students: 650,
    rating: 4.7,
    fees: "35,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Excellence in education with beautiful lakeside campus near Lake Tana.",
  },
  {
    id: 3,
    name: "Highland Preparatory School",
    slug: "highland-preparatory",
    location: "Gondar",
    region: "Amhara",
    type: "Private",
    students: 720,
    rating: 4.6,
    fees: "32,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Historic city location with modern educational facilities and rich cultural heritage.",
  },
  {
    id: 4,
    name: "Rift Valley International School",
    slug: "rift-valley-international",
    location: "Hawassa",
    region: "SNNPR",
    type: "International",
    students: 580,
    rating: 4.5,
    fees: "42,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "International curriculum in the beautiful Rift Valley region.",
  },
  {
    id: 5,
    name: "Jimma Excellence Academy",
    slug: "jimma-excellence-academy",
    location: "Jimma",
    region: "Oromia",
    type: "Private",
    students: 690,
    rating: 4.4,
    fees: "28,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Quality education in the heart of Ethiopia's coffee region.",
  },
  {
    id: 6,
    name: "Mekelle International Boarding",
    slug: "mekelle-international",
    location: "Mekelle",
    region: "Tigray",
    type: "International",
    students: 540,
    rating: 4.3,
    fees: "38,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Modern facilities and international standards in northern Ethiopia.",
  },
  {
    id: 7,
    name: "Dire Dawa Preparatory School",
    slug: "dire-dawa-preparatory",
    location: "Dire Dawa",
    region: "Dire Dawa",
    type: "Public",
    students: 800,
    rating: 4.2,
    fees: "15,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Established boarding school in the historic railway city.",
  },
  {
    id: 8,
    name: "Adama Science Academy",
    slug: "adama-science-academy",
    location: "Adama",
    region: "Oromia",
    type: "Private",
    students: 620,
    rating: 4.6,
    fees: "33,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Specialized in science and technology education with modern laboratories.",
  },
  {
    id: 9,
    name: "Dessie Mountain School",
    slug: "dessie-mountain-school",
    location: "Dessie",
    region: "Amhara",
    type: "Private",
    students: 480,
    rating: 4.1,
    fees: "26,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Scenic mountain location with focus on environmental studies.",
  },
  {
    id: 10,
    name: "Harar Heritage Academy",
    slug: "harar-heritage-academy",
    location: "Harar",
    region: "Harari",
    type: "Private",
    students: 420,
    rating: 4.4,
    fees: "30,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Cultural immersion and academic excellence in the historic city of Harar.",
  },
  {
    id: 11,
    name: "Nekemte International School",
    slug: "nekemte-international",
    location: "Nekemte",
    region: "Oromia",
    type: "International",
    students: 380,
    rating: 4.0,
    fees: "36,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "International education standards in western Ethiopia.",
  },
  {
    id: 12,
    name: "Debre Markos Preparatory",
    slug: "debre-markos-preparatory",
    location: "Debre Markos",
    region: "Amhara",
    type: "Public",
    students: 750,
    rating: 3.9,
    fees: "18,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Well-established public boarding school with strong academic tradition.",
  },
  {
    id: 13,
    name: "Arba Minch Lakeside Academy",
    slug: "arba-minch-lakeside",
    location: "Arba Minch",
    region: "SNNPR",
    type: "Private",
    students: 520,
    rating: 4.3,
    fees: "29,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Beautiful lakeside campus with focus on environmental conservation.",
  },
  {
    id: 14,
    name: "Axum Historical School",
    slug: "axum-historical-school",
    location: "Axum",
    region: "Tigray",
    type: "Private",
    students: 350,
    rating: 4.2,
    fees: "27,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Education rooted in Ethiopia's ancient history and traditions.",
  },
  {
    id: 15,
    name: "Shashemene International",
    slug: "shashemene-international",
    location: "Shashemene",
    region: "Oromia",
    type: "International",
    students: 460,
    rating: 4.1,
    fees: "34,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Diverse international community with multicultural education approach.",
  },
  {
    id: 16,
    name: "Kombolcha Technical School",
    slug: "kombolcha-technical",
    location: "Kombolcha",
    region: "Amhara",
    type: "Technical",
    students: 600,
    rating: 4.0,
    fees: "25,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Specialized technical and vocational education with modern workshops.",
  },
  {
    id: 17,
    name: "Wolkite Excellence Center",
    slug: "wolkite-excellence-center",
    location: "Wolkite",
    region: "SNNPR",
    type: "Private",
    students: 440,
    rating: 3.8,
    fees: "24,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Comprehensive education with strong community connections.",
  },
  {
    id: 18,
    name: "Debre Birhan Highland Academy",
    slug: "debre-birhan-highland",
    location: "Debre Birhan",
    region: "Amhara",
    type: "Private",
    students: 580,
    rating: 4.2,
    fees: "31,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "High-altitude campus with excellent air quality and mountain views.",
  },
  {
    id: 19,
    name: "Gambella International School",
    slug: "gambella-international",
    location: "Gambella",
    region: "Gambella",
    type: "International",
    students: 320,
    rating: 3.9,
    fees: "37,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "International education in Ethiopia's western frontier region.",
  },
  {
    id: 20,
    name: "Wolaita Sodo Academy",
    slug: "wolaita-sodo-academy",
    location: "Wolaita Sodo",
    region: "SNNPR",
    type: "Private",
    students: 510,
    rating: 4.1,
    fees: "26,500 ETB/year",
    image: getRandomSchoolImage(),
    description: "Strong academic programs with cultural preservation focus.",
  },
  {
    id: 21,
    name: "Dilla University Preparatory",
    slug: "dilla-university-prep",
    location: "Dilla",
    region: "SNNPR",
    type: "University Prep",
    students: 640,
    rating: 4.3,
    fees: "28,500 ETB/year",
    image: getRandomSchoolImage(),
    description: "Excellent university preparation with high acceptance rates.",
  },
  {
    id: 22,
    name: "Bonga Coffee Academy",
    slug: "bonga-coffee-academy",
    location: "Bonga",
    region: "SNNPR",
    type: "Specialized",
    students: 280,
    rating: 4.0,
    fees: "23,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Unique focus on agricultural sciences and coffee cultivation.",
  },
  {
    id: 23,
    name: "Debre Zeit Aviation School",
    slug: "debre-zeit-aviation",
    location: "Debre Zeit",
    region: "Oromia",
    type: "Specialized",
    students: 360,
    rating: 4.4,
    fees: "40,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Specialized aviation and aerospace education programs.",
  },
  {
    id: 24,
    name: "Mizan Teferi Forest Academy",
    slug: "mizan-teferi-forest",
    location: "Mizan Teferi",
    region: "SNNPR",
    type: "Environmental",
    students: 390,
    rating: 3.9,
    fees: "22,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Environmental education in Ethiopia's coffee forest region.",
  },
  {
    id: 25,
    name: "Assosa Border Academy",
    slug: "assosa-border-academy",
    location: "Assosa",
    region: "Benishangul-Gumuz",
    type: "Private",
    students: 310,
    rating: 3.7,
    fees: "21,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Cross-cultural education near the Sudanese border.",
  },
  {
    id: 26,
    name: "Semera Desert School",
    slug: "semera-desert-school",
    location: "Semera",
    region: "Afar",
    type: "Specialized",
    students: 250,
    rating: 3.8,
    fees: "35,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Unique desert environment education with geological focus.",
  },
  {
    id: 27,
    name: "Jijiga Pastoral Academy",
    slug: "jijiga-pastoral-academy",
    location: "Jijiga",
    region: "Somali",
    type: "Cultural",
    students: 420,
    rating: 3.9,
    fees: "24,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Education that honors pastoral traditions and modern academics.",
  },
  {
    id: 28,
    name: "Finote Selam Mountain School",
    slug: "finote-selam-mountain",
    location: "Finote Selam",
    region: "Amhara",
    type: "Private",
    students: 380,
    rating: 4.0,
    fees: "25,500 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Mountain campus with focus on outdoor education and leadership.",
  },
  {
    id: 29,
    name: "Welkite Agricultural School",
    slug: "welkite-agricultural",
    location: "Welkite",
    region: "SNNPR",
    type: "Agricultural",
    students: 480,
    rating: 4.1,
    fees: "20,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Hands-on agricultural education with working farm campus.",
  },
  {
    id: 30,
    name: "Debre Tabor Highland Institute",
    slug: "debre-tabor-highland",
    location: "Debre Tabor",
    region: "Amhara",
    type: "Private",
    students: 520,
    rating: 4.2,
    fees: "29,500 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "High-altitude learning environment with excellent facilities.",
  },
  {
    id: 31,
    name: "Hosanna Christian Academy",
    slug: "hosanna-christian-academy",
    location: "Hosanna",
    region: "SNNPR",
    type: "Religious",
    students: 450,
    rating: 4.3,
    fees: "27,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Faith-based education with strong moral and academic foundation.",
  },
  {
    id: 32,
    name: "Sebeta International School",
    slug: "sebeta-international",
    location: "Sebeta",
    region: "Oromia",
    type: "International",
    students: 680,
    rating: 4.5,
    fees: "41,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Modern international school near Addis Ababa with global curriculum.",
  },
  {
    id: 33,
    name: "Butajira Science Center",
    slug: "butajira-science-center",
    location: "Butajira",
    region: "SNNPR",
    type: "Science",
    students: 410,
    rating: 4.1,
    fees: "32,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "STEM-focused education with advanced laboratory facilities.",
  },
  {
    id: 34,
    name: "Ziway Lakeside School",
    slug: "ziway-lakeside-school",
    location: "Ziway",
    region: "Oromia",
    type: "Private",
    students: 360,
    rating: 3.9,
    fees: "26,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Beautiful lakeside campus with water sports and environmental programs.",
  },
  {
    id: 35,
    name: "Metu Forest Academy",
    slug: "metu-forest-academy",
    location: "Metu",
    region: "Oromia",
    type: "Environmental",
    students: 330,
    rating: 4.0,
    fees: "23,500 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Environmental conservation education in pristine forest setting.",
  },
  {
    id: 36,
    name: "Woldiya Technical Institute",
    slug: "woldiya-technical",
    location: "Woldiya",
    region: "Amhara",
    type: "Technical",
    students: 550,
    rating: 4.0,
    fees: "24,500 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Technical and vocational training with industry partnerships.",
  },
  {
    id: 37,
    name: "Robe Mountain Academy",
    slug: "robe-mountain-academy",
    location: "Robe",
    region: "Oromia",
    type: "Private",
    students: 290,
    rating: 3.8,
    fees: "22,500 ETB/year",
    image: getRandomSchoolImage(),
    description: "High-altitude education with focus on mountain ecology.",
  },
  {
    id: 38,
    name: "Goba Highland School",
    slug: "goba-highland-school",
    location: "Goba",
    region: "Oromia",
    type: "Private",
    students: 340,
    rating: 4.1,
    fees: "28,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Mountain education with outdoor adventure programs.",
  },
  {
    id: 39,
    name: "Yirgalem Coffee School",
    slug: "yirgalem-coffee-school",
    location: "Yirgalem",
    region: "SNNPR",
    type: "Agricultural",
    students: 380,
    rating: 4.2,
    fees: "21,500 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Agricultural education specializing in coffee cultivation and processing.",
  },
  {
    id: 40,
    name: "Adigrat Border Academy",
    slug: "adigrat-border-academy",
    location: "Adigrat",
    region: "Tigray",
    type: "Private",
    students: 400,
    rating: 3.9,
    fees: "25,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Cross-border educational programs with Eritrean cultural exchange.",
  },
  {
    id: 41,
    name: "Gimbi Agricultural Institute",
    slug: "gimbi-agricultural",
    location: "Gimbi",
    region: "Oromia",
    type: "Agricultural",
    students: 460,
    rating: 4.0,
    fees: "19,500 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Comprehensive agricultural education with modern farming techniques.",
  },
  {
    id: 42,
    name: "Tepi Forest College",
    slug: "tepi-forest-college",
    location: "Tepi",
    region: "SNNPR",
    type: "Environmental",
    students: 270,
    rating: 3.8,
    fees: "20,500 ETB/year",
    image: getRandomSchoolImage(),
    description: "Forest conservation and environmental science education.",
  },
  {
    id: 43,
    name: "Awash Valley School",
    slug: "awash-valley-school",
    location: "Awash",
    region: "Afar",
    type: "Specialized",
    students: 320,
    rating: 3.7,
    fees: "33,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Unique geological and archaeological education programs.",
  },
  {
    id: 44,
    name: "Moyale Border Institute",
    slug: "moyale-border-institute",
    location: "Moyale",
    region: "Oromia",
    type: "Cultural",
    students: 280,
    rating: 3.6,
    fees: "23,500 ETB/year",
    image: getRandomSchoolImage(),
    description: "Cross-cultural education at the Kenya-Ethiopia border.",
  },
  {
    id: 45,
    name: "Lalibela Heritage School",
    slug: "lalibela-heritage-school",
    location: "Lalibela",
    region: "Amhara",
    type: "Cultural",
    students: 350,
    rating: 4.4,
    fees: "30,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Education immersed in Ethiopia's UNESCO World Heritage site.",
  },
  {
    id: 46,
    name: "Holeta Agricultural College",
    slug: "holeta-agricultural",
    location: "Holeta",
    region: "Oromia",
    type: "Agricultural",
    students: 520,
    rating: 4.2,
    fees: "22,000 ETB/year",
    image: getRandomSchoolImage(),
    description: "Leading agricultural research and education institution.",
  },
  {
    id: 47,
    name: "Bale Mountain Academy",
    slug: "bale-mountain-academy",
    location: "Bale",
    region: "Oromia",
    type: "Environmental",
    students: 240,
    rating: 4.3,
    fees: "31,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "High-altitude education in Bale Mountains National Park area.",
  },
  {
    id: 48,
    name: "Kebridehar Pastoral School",
    slug: "kebridehar-pastoral",
    location: "Kebridehar",
    region: "Somali",
    type: "Cultural",
    students: 300,
    rating: 3.8,
    fees: "20,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Education that bridges traditional pastoral life and modern academics.",
  },
  {
    id: 49,
    name: "Metahara Sugar Academy",
    slug: "metahara-sugar-academy",
    location: "Metahara",
    region: "Oromia",
    type: "Industrial",
    students: 410,
    rating: 3.9,
    fees: "26,500 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Industrial education with focus on sugar processing and agriculture.",
  },
  {
    id: 50,
    name: "Simien Mountain School",
    slug: "simien-mountain-school",
    location: "Simien Mountains",
    region: "Amhara",
    type: "Environmental",
    students: 180,
    rating: 4.5,
    fees: "35,000 ETB/year",
    image: getRandomSchoolImage(),
    description:
      "Exclusive mountain education in UNESCO World Heritage landscape.",
  },
];

// Helper functions for filtering and searching schools
export const filterSchools = (query: string): School[] => {
  if (query.trim() === "") {
    return schools;
  }

  return schools.filter(
    (school) =>
      school.name.toLowerCase().includes(query.toLowerCase()) ||
      school.location.toLowerCase().includes(query.toLowerCase()) ||
      school.region.toLowerCase().includes(query.toLowerCase()) ||
      school.type.toLowerCase().includes(query.toLowerCase()) ||
      school.description.toLowerCase().includes(query.toLowerCase())
  );
};

export const getSchoolBySlug = (slug: string): School | undefined => {
  return schools.find((school) => school.slug === slug);
};

export const getFeaturedSchools = (count = 3): School[] => {
  return schools.slice(0, count);
};

export const getSchoolsByRegion = (region: string): School[] => {
  return schools.filter(
    (school) => school.region.toLowerCase() === region.toLowerCase()
  );
};

export const getSchoolsByType = (type: string): School[] => {
  return schools.filter(
    (school) => school.type.toLowerCase() === type.toLowerCase()
  );
};

// Export the school images list for potential use elsewhere
export { schoolImagesList };
